version: "3"

services:
  webserver:
    image: node:9.11.1-alpine
    command: "npm start"
    working_dir: "/app"
    volumes:
        - ./:/app
        - ./logs/node:/var/log/
    ports:
        - 80:80
    links:
        - mongo
    depends_on:
        - mongo
  mongo:
    image: bitnami/mongodb:latest
    ports:
        - 27017:27017


